repos:
-   repo: local
    hooks:
    - id: format
      name: format
      language: system
      entry: make format
      types: [python]
    - id: lint
      name: lint
      language: system
      entry: make lint
      types: [python]
    # - id: utest
    #   name: utest
    #   language: system
    #   entry: make utest
    #   types: [python]