name: check pr convention

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          max_length: 72